version: "3.9"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beauty_ecom
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    environment:
      - PORT=4000
      - DB_URI=mysql://app:app@mysql:3306/beauty_ecom
      - JWT_SECRET=devsecret
      - ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data:
